@baseUrl = http://localhost:3333

# @name register_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com"
}

###

# @name create_meal
POST {{baseUrl}}/meals
Content-Type: application/json

{
  "name": "Breakfast",
  "description": "Bread with jam and coffee",
  "isOnDiet": true,
  "date": "2024-06-05T10:00:00.000Z"
}

###

# @name fetch_meals
GET {{baseUrl}}/meals
Content-Type: application/json